name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-client:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ${{ env.workdir-client }}
      run: yarn

    - name: Run the tests and generate coverage report
      working-directory: ${{ env.workdir-client }}
      run: yarn test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Build
      working-directory: ${{ env.workdir-client }}
      run: yarn build
      
  